// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from "@prisma/orm-postgres/adapter/operation-types";
import type { CodecTypes as PgTypes } from "@prisma/orm-postgres/target/codec-types";

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from "@prisma/orm-postgres/family-contract/types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-postgres/contract/types";

export type StorageHash =
  StorageHashBase<"6377e50a2422af260db76d72fe1b4a17d2efbe0a6baf41330a93e9f1601e8185">;
export type ExecutionHash =
  ExecutionHashBase<"09818f12e2870f575434944ca2dcc71b55f6e63a8685ad14ea8773a9d90c7bda">;
export type ProfileHash =
  ProfileHashBase<"3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2">;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly "pg/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly "pg/int@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: "pg/int8number@1";
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: "pg/int8number@1";
      readonly nullable: false;
    };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: "pg/int8@1";
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: "pg/int8@1";
      readonly nullable: false;
    };
  };
  readonly max: {
    readonly byCodec: {
      readonly "pg/char@1": {
        readonly output: "pg/char@1";
        readonly nullable: true;
      };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": {
        readonly output: "pg/enum@1";
        readonly nullable: true;
      };
      readonly "pg/float@1": {
        readonly output: "pg/float@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/inet@1": {
        readonly output: "pg/inet@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int2@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int4@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": {
        readonly output: "pg/timetz@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "sql/char@1": {
        readonly output: "sql/char@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "sql/float@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "sql/int@1";
        readonly nullable: true;
      };
      readonly "sql/text@1": {
        readonly output: "sql/text@1";
        readonly nullable: true;
      };
      readonly "sql/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly "pg/char@1": {
        readonly output: "pg/char@1";
        readonly nullable: true;
      };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": {
        readonly output: "pg/enum@1";
        readonly nullable: true;
      };
      readonly "pg/float@1": {
        readonly output: "pg/float@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/inet@1": {
        readonly output: "pg/inet@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int2@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int4@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": {
        readonly output: "pg/timetz@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "sql/char@1": {
        readonly output: "sql/char@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "sql/float@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "sql/int@1";
        readonly nullable: true;
      };
      readonly "sql/text@1": {
        readonly output: "sql/text@1";
        readonly nullable: true;
      };
      readonly "sql/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly "pg/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly "pg/int@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
    };
  };
};
type DefaultLiteralValue<
  CodecId extends string,
  Encoded,
> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]["json"]
    ? Encoded
    : CodecTypes[CodecId]["json"]
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Account: {
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly userId: CodecTypes["pg/int4@1"]["output"];
      readonly accountId: CodecTypes["pg/text@1"]["output"];
      readonly providerId: CodecTypes["pg/text@1"]["output"];
      readonly password: CodecTypes["pg/text@1"]["output"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly accessToken: CodecTypes["pg/text@1"]["output"] | null;
      readonly refreshToken: CodecTypes["pg/text@1"]["output"] | null;
      readonly accessTokenExpiresAt:
        CodecTypes["pg/timestamptz-string@1"]["output"] | null;
      readonly refreshTokenExpiresAt:
        CodecTypes["pg/timestamptz-string@1"]["output"] | null;
      readonly scope: CodecTypes["pg/text@1"]["output"] | null;
      readonly idToken: CodecTypes["pg/text@1"]["output"] | null;
    };
    readonly Bookmark: {
      readonly userId: CodecTypes["pg/int4@1"]["output"];
      readonly noteId: CodecTypes["pg/int4@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly Folder: {
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly parentFolderId: CodecTypes["pg/int4@1"]["output"] | null;
      readonly slug: CodecTypes["pg/text@1"]["output"];
      readonly publishedAt:
        CodecTypes["pg/timestamptz-string@1"]["output"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly Note: {
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly title: CodecTypes["pg/text@1"]["output"];
      readonly slug: CodecTypes["pg/text@1"]["output"];
      readonly content: CodecTypes["pg/text@1"]["output"];
      readonly folderId: CodecTypes["pg/int4@1"]["output"] | null;
      readonly publishedAt:
        CodecTypes["pg/timestamptz-string@1"]["output"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly ReadingProgress: {
      readonly userId: CodecTypes["pg/int4@1"]["output"];
      readonly noteId: CodecTypes["pg/int4@1"]["output"];
      readonly sectionName: CodecTypes["pg/text@1"]["output"] | null;
      readonly progress: CodecTypes["pg/int4@1"]["output"];
      readonly scrollPosition: CodecTypes["pg/int4@1"]["output"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly Session: {
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly token: CodecTypes["pg/text@1"]["output"];
      readonly userId: CodecTypes["pg/int4@1"]["output"];
      readonly expiresAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly ipAddress: CodecTypes["pg/text@1"]["output"] | null;
      readonly serAgent: CodecTypes["pg/text@1"]["output"] | null;
    };
    readonly User: {
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly username: CodecTypes["pg/text@1"]["output"];
      readonly role: "USER" | "ADMIN";
      readonly emailVerified: CodecTypes["pg/bool@1"]["output"];
      readonly image: CodecTypes["pg/text@1"]["output"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly Verification: {
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly identifier: CodecTypes["pg/text@1"]["output"];
      readonly value: CodecTypes["pg/text@1"]["output"];
      readonly expiresAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Account: {
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly userId: CodecTypes["pg/int4@1"]["input"];
      readonly accountId: CodecTypes["pg/text@1"]["input"];
      readonly providerId: CodecTypes["pg/text@1"]["input"];
      readonly password: CodecTypes["pg/text@1"]["input"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly accessToken: CodecTypes["pg/text@1"]["input"] | null;
      readonly refreshToken: CodecTypes["pg/text@1"]["input"] | null;
      readonly accessTokenExpiresAt:
        CodecTypes["pg/timestamptz-string@1"]["input"] | null;
      readonly refreshTokenExpiresAt:
        CodecTypes["pg/timestamptz-string@1"]["input"] | null;
      readonly scope: CodecTypes["pg/text@1"]["input"] | null;
      readonly idToken: CodecTypes["pg/text@1"]["input"] | null;
    };
    readonly Bookmark: {
      readonly userId: CodecTypes["pg/int4@1"]["input"];
      readonly noteId: CodecTypes["pg/int4@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly Folder: {
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly parentFolderId: CodecTypes["pg/int4@1"]["input"] | null;
      readonly slug: CodecTypes["pg/text@1"]["input"];
      readonly publishedAt:
        CodecTypes["pg/timestamptz-string@1"]["input"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly Note: {
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly title: CodecTypes["pg/text@1"]["input"];
      readonly slug: CodecTypes["pg/text@1"]["input"];
      readonly content: CodecTypes["pg/text@1"]["input"];
      readonly folderId: CodecTypes["pg/int4@1"]["input"] | null;
      readonly publishedAt:
        CodecTypes["pg/timestamptz-string@1"]["input"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly ReadingProgress: {
      readonly userId: CodecTypes["pg/int4@1"]["input"];
      readonly noteId: CodecTypes["pg/int4@1"]["input"];
      readonly sectionName: CodecTypes["pg/text@1"]["input"] | null;
      readonly progress: CodecTypes["pg/int4@1"]["input"];
      readonly scrollPosition: CodecTypes["pg/int4@1"]["input"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly Session: {
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly token: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["pg/int4@1"]["input"];
      readonly expiresAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly ipAddress: CodecTypes["pg/text@1"]["input"] | null;
      readonly serAgent: CodecTypes["pg/text@1"]["input"] | null;
    };
    readonly User: {
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly username: CodecTypes["pg/text@1"]["input"];
      readonly role: "USER" | "ADMIN";
      readonly emailVerified: CodecTypes["pg/bool@1"]["input"];
      readonly image: CodecTypes["pg/text@1"]["input"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly Verification: {
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly identifier: CodecTypes["pg/text@1"]["input"];
      readonly value: CodecTypes["pg/text@1"]["input"];
      readonly expiresAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly account: {
      readonly accessToken: CodecTypes["pg/text@1"]["output"] | null;
      readonly accessTokenExpiresAt:
        CodecTypes["pg/timestamptz-string@1"]["output"] | null;
      readonly accountId: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly idToken: CodecTypes["pg/text@1"]["output"] | null;
      readonly password: CodecTypes["pg/text@1"]["output"] | null;
      readonly providerId: CodecTypes["pg/text@1"]["output"];
      readonly refreshToken: CodecTypes["pg/text@1"]["output"] | null;
      readonly refreshTokenExpiresAt:
        CodecTypes["pg/timestamptz-string@1"]["output"] | null;
      readonly scope: CodecTypes["pg/text@1"]["output"] | null;
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly userId: CodecTypes["pg/int4@1"]["output"];
    };
    readonly bookmark: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly noteId: CodecTypes["pg/int4@1"]["output"];
      readonly userId: CodecTypes["pg/int4@1"]["output"];
    };
    readonly folder: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly parentFolderId: CodecTypes["pg/int4@1"]["output"] | null;
      readonly publishedAt:
        CodecTypes["pg/timestamptz-string@1"]["output"] | null;
      readonly slug: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly note: {
      readonly content: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly folderId: CodecTypes["pg/int4@1"]["output"] | null;
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly publishedAt:
        CodecTypes["pg/timestamptz-string@1"]["output"] | null;
      readonly slug: CodecTypes["pg/text@1"]["output"];
      readonly title: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly reading_progress: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly noteId: CodecTypes["pg/int4@1"]["output"];
      readonly progress: CodecTypes["pg/int4@1"]["output"];
      readonly scrollPosition: CodecTypes["pg/int4@1"]["output"] | null;
      readonly sectionName: CodecTypes["pg/text@1"]["output"] | null;
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly userId: CodecTypes["pg/int4@1"]["output"];
    };
    readonly session: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly expiresAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly ipAddress: CodecTypes["pg/text@1"]["output"] | null;
      readonly serAgent: CodecTypes["pg/text@1"]["output"] | null;
      readonly token: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly userId: CodecTypes["pg/int4@1"]["output"];
    };
    readonly user: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly emailVerified: CodecTypes["pg/bool@1"]["output"];
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly image: CodecTypes["pg/text@1"]["output"] | null;
      readonly role: "USER" | "ADMIN";
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly username: CodecTypes["pg/text@1"]["output"];
    };
    readonly verification: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly expiresAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly id: CodecTypes["pg/int4@1"]["output"];
      readonly identifier: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly value: CodecTypes["pg/text@1"]["output"];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly account: {
      readonly accessToken: CodecTypes["pg/text@1"]["input"] | null;
      readonly accessTokenExpiresAt:
        CodecTypes["pg/timestamptz-string@1"]["input"] | null;
      readonly accountId: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly idToken: CodecTypes["pg/text@1"]["input"] | null;
      readonly password: CodecTypes["pg/text@1"]["input"] | null;
      readonly providerId: CodecTypes["pg/text@1"]["input"];
      readonly refreshToken: CodecTypes["pg/text@1"]["input"] | null;
      readonly refreshTokenExpiresAt:
        CodecTypes["pg/timestamptz-string@1"]["input"] | null;
      readonly scope: CodecTypes["pg/text@1"]["input"] | null;
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly userId: CodecTypes["pg/int4@1"]["input"];
    };
    readonly bookmark: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly noteId: CodecTypes["pg/int4@1"]["input"];
      readonly userId: CodecTypes["pg/int4@1"]["input"];
    };
    readonly folder: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly parentFolderId: CodecTypes["pg/int4@1"]["input"] | null;
      readonly publishedAt:
        CodecTypes["pg/timestamptz-string@1"]["input"] | null;
      readonly slug: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly note: {
      readonly content: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly folderId: CodecTypes["pg/int4@1"]["input"] | null;
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly publishedAt:
        CodecTypes["pg/timestamptz-string@1"]["input"] | null;
      readonly slug: CodecTypes["pg/text@1"]["input"];
      readonly title: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly reading_progress: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly noteId: CodecTypes["pg/int4@1"]["input"];
      readonly progress: CodecTypes["pg/int4@1"]["input"];
      readonly scrollPosition: CodecTypes["pg/int4@1"]["input"] | null;
      readonly sectionName: CodecTypes["pg/text@1"]["input"] | null;
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly userId: CodecTypes["pg/int4@1"]["input"];
    };
    readonly session: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly expiresAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly ipAddress: CodecTypes["pg/text@1"]["input"] | null;
      readonly serAgent: CodecTypes["pg/text@1"]["input"] | null;
      readonly token: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly userId: CodecTypes["pg/int4@1"]["input"];
    };
    readonly user: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly emailVerified: CodecTypes["pg/bool@1"]["input"];
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly image: CodecTypes["pg/text@1"]["input"] | null;
      readonly role: "USER" | "ADMIN";
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly username: CodecTypes["pg/text@1"]["input"];
    };
    readonly verification: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly expiresAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly id: CodecTypes["pg/int4@1"]["input"];
      readonly identifier: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly value: CodecTypes["pg/text@1"]["input"];
    };
  };
};

export namespace Models {
  export type public_User = {
    id: CodecTypes["pg/int4@1"]["output"];
    email: CodecTypes["pg/text@1"]["output"];
    username: CodecTypes["pg/text@1"]["output"];
    role: "USER" | "ADMIN";
    emailVerified: CodecTypes["pg/bool@1"]["output"];
    image: CodecTypes["pg/text@1"]["output"] | null;
    createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    bookmarks: public_Bookmark[];
    readingProgress: public_ReadingProgress[];
    sessions: public_Session[];
    readonly [RelationKeys]?: "bookmarks" | "readingProgress" | "sessions";
  };
  export type public_Session = {
    id: CodecTypes["pg/int4@1"]["output"];
    token: CodecTypes["pg/text@1"]["output"];
    userId: CodecTypes["pg/int4@1"]["output"];
    expiresAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    ipAddress: CodecTypes["pg/text@1"]["output"] | null;
    serAgent: CodecTypes["pg/text@1"]["output"] | null;
    user: public_User;
    readonly [RelationKeys]?: "user";
  };
  export type public_Account = {
    id: CodecTypes["pg/int4@1"]["output"];
    userId: CodecTypes["pg/int4@1"]["output"];
    accountId: CodecTypes["pg/text@1"]["output"];
    providerId: CodecTypes["pg/text@1"]["output"];
    password: CodecTypes["pg/text@1"]["output"] | null;
    createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    accessToken: CodecTypes["pg/text@1"]["output"] | null;
    refreshToken: CodecTypes["pg/text@1"]["output"] | null;
    accessTokenExpiresAt:
      CodecTypes["pg/timestamptz-string@1"]["output"] | null;
    refreshTokenExpiresAt:
      CodecTypes["pg/timestamptz-string@1"]["output"] | null;
    scope: CodecTypes["pg/text@1"]["output"] | null;
    idToken: CodecTypes["pg/text@1"]["output"] | null;
    user: public_User;
    readonly [RelationKeys]?: "user";
  };
  export type public_Verification = {
    id: CodecTypes["pg/int4@1"]["output"];
    identifier: CodecTypes["pg/text@1"]["output"];
    value: CodecTypes["pg/text@1"]["output"];
    expiresAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    readonly [RelationKeys]?: never;
  };
  export type public_Folder = {
    id: CodecTypes["pg/int4@1"]["output"];
    name: CodecTypes["pg/text@1"]["output"];
    parentFolderId: CodecTypes["pg/int4@1"]["output"] | null;
    slug: CodecTypes["pg/text@1"]["output"];
    publishedAt: CodecTypes["pg/timestamptz-string@1"]["output"] | null;
    createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    children: public_Folder[];
    notes: public_Note[];
    parent: public_Folder | null;
    readonly [RelationKeys]?: "children" | "notes" | "parent";
  };
  export type public_Note = {
    id: CodecTypes["pg/int4@1"]["output"];
    title: CodecTypes["pg/text@1"]["output"];
    slug: CodecTypes["pg/text@1"]["output"];
    content: CodecTypes["pg/text@1"]["output"];
    folderId: CodecTypes["pg/int4@1"]["output"] | null;
    publishedAt: CodecTypes["pg/timestamptz-string@1"]["output"] | null;
    createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    bookmarks: public_Bookmark[];
    folder: public_Folder | null;
    readingProgress: public_ReadingProgress[];
    readonly [RelationKeys]?: "bookmarks" | "folder" | "readingProgress";
  };
  export type public_Bookmark = {
    userId: CodecTypes["pg/int4@1"]["output"];
    noteId: CodecTypes["pg/int4@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    note: public_Note;
    user: public_User;
    readonly [RelationKeys]?: "note" | "user";
  };
  export type public_ReadingProgress = {
    userId: CodecTypes["pg/int4@1"]["output"];
    noteId: CodecTypes["pg/int4@1"]["output"];
    sectionName: CodecTypes["pg/text@1"]["output"] | null;
    progress: CodecTypes["pg/int4@1"]["output"];
    scrollPosition: CodecTypes["pg/int4@1"]["output"] | null;
    createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    note: public_Note;
    user: public_User;
    readonly [RelationKeys]?: "note" | "user";
  };
}

export declare const models: {
  public: {
    User: Models.public_User;
    Session: Models.public_Session;
    Account: Models.public_Account;
    Verification: Models.public_Verification;
    Folder: Models.public_Folder;
    Note: Models.public_Note;
    Bookmark: Models.public_Bookmark;
    ReadingProgress: Models.public_ReadingProgress;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: "public";
        readonly kind: "postgres-schema";
        readonly entries: {
          readonly table: {
            readonly account: {
              columns: {
                readonly id: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "autoincrement()";
                  };
                };
                readonly userId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly accountId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly providerId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly password: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
                readonly accessToken: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly refreshToken: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly accessTokenExpiresAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: true;
                };
                readonly refreshTokenExpiresAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: true;
                };
                readonly scope: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly idToken: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "account_userId_idx_a489d58a";
                  readonly prefix: "account_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "account";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly bookmark: {
              columns: {
                readonly userId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly noteId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
              };
              primaryKey: { readonly columns: readonly ["userId", "noteId"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "bookmark_userId_idx_a489d58a";
                  readonly prefix: "bookmark_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
                {
                  readonly name: "bookmark_noteId_idx_0612c5b1";
                  readonly prefix: "bookmark_noteId_idx";
                  readonly columns: readonly ["noteId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "bookmark";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "bookmark";
                    readonly columns: readonly ["noteId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "note";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly folder: {
              columns: {
                readonly id: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "autoincrement()";
                  };
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly parentFolderId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: true;
                };
                readonly slug: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly publishedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["slug"] }];
              indexes: readonly [
                {
                  readonly name: "folder_parentFolderId_idx_66fef1f5";
                  readonly prefix: "folder_parentFolderId_idx";
                  readonly columns: readonly ["parentFolderId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "folder";
                    readonly columns: readonly ["parentFolderId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "folder";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly note: {
              columns: {
                readonly id: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "autoincrement()";
                  };
                };
                readonly title: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly content: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly folderId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: true;
                };
                readonly publishedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["slug"] }];
              indexes: readonly [
                {
                  readonly name: "note_folderId_idx_5985e562";
                  readonly prefix: "note_folderId_idx";
                  readonly columns: readonly ["folderId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "note";
                    readonly columns: readonly ["folderId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "folder";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly reading_progress: {
              columns: {
                readonly userId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly noteId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly sectionName: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly progress: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly scrollPosition: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["userId", "noteId"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "reading_progress_userId_idx_a489d58a";
                  readonly prefix: "reading_progress_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
                {
                  readonly name: "reading_progress_noteId_idx_0612c5b1";
                  readonly prefix: "reading_progress_noteId_idx";
                  readonly columns: readonly ["noteId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "reading_progress";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "reading_progress";
                    readonly columns: readonly ["noteId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "note";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly session: {
              columns: {
                readonly id: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "autoincrement()";
                  };
                };
                readonly token: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly expiresAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
                readonly ipAddress: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly serAgent: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["token"] }];
              indexes: readonly [
                {
                  readonly name: "session_userId_idx_a489d58a";
                  readonly prefix: "session_userId_idx";
                  readonly columns: readonly ["userId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "session";
                    readonly columns: readonly ["userId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "user";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "autoincrement()";
                  };
                };
                readonly email: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly username: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", "USER">;
                  };
                };
                readonly emailVerified: {
                  readonly nativeType: "bool";
                  readonly codecId: "pg/bool@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/bool@1", false>;
                  };
                };
                readonly image: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [
                { readonly columns: readonly ["email"] },
                { readonly columns: readonly ["username"] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly verification: {
              columns: {
                readonly id: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "autoincrement()";
                  };
                };
                readonly identifier: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly value: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly expiresAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly Role: {
              readonly kind: "valueSet";
              readonly values: readonly ["USER", "ADMIN"];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly user: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "User";
    };
    readonly session: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Session";
    };
    readonly account: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Account";
    };
    readonly verification: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Verification";
    };
    readonly folder: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Folder";
    };
    readonly note: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Note";
    };
    readonly bookmark: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Bookmark";
    };
    readonly reading_progress: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "ReadingProgress";
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Account: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly accountId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly providerId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly password: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly accessToken: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly refreshToken: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly accessTokenExpiresAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly refreshTokenExpiresAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly scope: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly idToken: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "User";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "account";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly userId: { readonly column: "userId" };
                readonly accountId: { readonly column: "accountId" };
                readonly providerId: { readonly column: "providerId" };
                readonly password: { readonly column: "password" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
                readonly accessToken: { readonly column: "accessToken" };
                readonly refreshToken: { readonly column: "refreshToken" };
                readonly accessTokenExpiresAt: {
                  readonly column: "accessTokenExpiresAt";
                };
                readonly refreshTokenExpiresAt: {
                  readonly column: "refreshTokenExpiresAt";
                };
                readonly scope: { readonly column: "scope" };
                readonly idToken: { readonly column: "idToken" };
              };
            };
          };
          readonly Bookmark: {
            readonly fields: {
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly noteId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: {
              readonly note: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Note";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["noteId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "User";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "bookmark";
              readonly namespaceId: "public";
              readonly fields: {
                readonly userId: { readonly column: "userId" };
                readonly noteId: { readonly column: "noteId" };
                readonly createdAt: { readonly column: "createdAt" };
              };
            };
          };
          readonly Folder: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly parentFolderId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly publishedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: {
              readonly children: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Folder";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["parentFolderId"];
                };
              };
              readonly notes: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Note";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["folderId"];
                };
              };
              readonly parent: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Folder";
                };
                readonly cardinality: "N:1";
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ["parentFolderId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "folder";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly parentFolderId: { readonly column: "parentFolderId" };
                readonly slug: { readonly column: "slug" };
                readonly publishedAt: { readonly column: "publishedAt" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
          readonly Note: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly folderId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly publishedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: {
              readonly bookmarks: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Bookmark";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["noteId"];
                };
              };
              readonly folder: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Folder";
                };
                readonly cardinality: "N:1";
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ["folderId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly readingProgress: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "ReadingProgress";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["noteId"];
                };
              };
            };
            readonly storage: {
              readonly table: "note";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly title: { readonly column: "title" };
                readonly slug: { readonly column: "slug" };
                readonly content: { readonly column: "content" };
                readonly folderId: { readonly column: "folderId" };
                readonly publishedAt: { readonly column: "publishedAt" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
          readonly ReadingProgress: {
            readonly fields: {
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly noteId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly sectionName: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly progress: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly scrollPosition: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: {
              readonly note: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Note";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["noteId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "User";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "reading_progress";
              readonly namespaceId: "public";
              readonly fields: {
                readonly userId: { readonly column: "userId" };
                readonly noteId: { readonly column: "noteId" };
                readonly sectionName: { readonly column: "sectionName" };
                readonly progress: { readonly column: "progress" };
                readonly scrollPosition: { readonly column: "scrollPosition" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
          readonly Session: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly token: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly ipAddress: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly serAgent: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "User";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "session";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly token: { readonly column: "token" };
                readonly userId: { readonly column: "userId" };
                readonly expiresAt: { readonly column: "expiresAt" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
                readonly ipAddress: { readonly column: "ipAddress" };
                readonly serAgent: { readonly column: "serAgent" };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly emailVerified: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/bool@1";
                };
              };
              readonly image: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: {
              readonly bookmarks: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Bookmark";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
              readonly readingProgress: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "ReadingProgress";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
              readonly sessions: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Session";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
            };
            readonly storage: {
              readonly table: "user";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly email: { readonly column: "email" };
                readonly username: { readonly column: "username" };
                readonly role: { readonly column: "role" };
                readonly emailVerified: { readonly column: "emailVerified" };
                readonly image: { readonly column: "image" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
          readonly Verification: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly identifier: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly value: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "verification";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly identifier: { readonly column: "identifier" };
                readonly value: { readonly column: "value" };
                readonly expiresAt: { readonly column: "expiresAt" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
        };
        readonly enum: {
          readonly Role: {
            readonly codecId: "pg/text@1";
            readonly members: readonly [
              { readonly name: "USER"; readonly value: "USER" },
              { readonly name: "ADMIN"; readonly value: "ADMIN" },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "account";
            readonly column: "updatedAt";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
          readonly onUpdate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "folder";
            readonly column: "updatedAt";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
          readonly onUpdate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "note";
            readonly column: "updatedAt";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
          readonly onUpdate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "reading_progress";
            readonly column: "updatedAt";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
          readonly onUpdate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "session";
            readonly column: "updatedAt";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
          readonly onUpdate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "user";
            readonly column: "updatedAt";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
          readonly onUpdate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "verification";
            readonly column: "updatedAt";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
          readonly onUpdate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
